### ISSUE TITLE
Potential for syncing wrong project exists (especially when switching projects)

### ISSUE THREAD

**Issue by Quenty** [LPGhatguy/rojo#23] opened 2017-12-17 21:41 UTC
Serving from the wrong repository makes rojo have the potential to serve bad content to a place. This in turns results in artifacts left in the place, which is bad.

**Comment by LPGhatguy** [comment] 2017-12-18 05:57
I have an idea for this.

When syncing into a place, I think Rojo should make a new `Folder` directly under game (probably called `Rojo`) that has project information. The UI can then pop up a warning when connecting to a server with a different project name!

It might have negative interactions with team create, but I think that Rojo already doesn't mesh well with that workflow. It should probably have warning dialogs there, too.

**Comment by LPGhatguy** [comment] 2018-06-14 00:30
Tinkered with this a bit, and I have two solutions lined up for 0.5.0:

* Each project will have a random port assigned to it (prompted on initial sync and saved into a folder named `Rojo`)
* When syncing a project, the name of the project is also saved into the `Rojo` folder, which helps in the case of collisions or other mistakes.

**Comment by LastTalon** [comment] 2018-06-14 11:28
I don't like the idea of Rojo adding instances to a game project for itself to use. I feel this is antithetical to my use of Rojo as a tool to help sync my file system project files into a game project. And I don't like the idea of a random port either, that seems very hacky.

The problem seems to be one to do with the way changes are committed to a project. While an automatic syncing method can be very useful in some circumstances, a workflow similar to git might be preferable in many cases where you either push or pull changes from the file system to the project.

This doesn't preclude a system that automatically syncs, but it would have to stop operating this way during a project change, so if either end were to disconnect the other should stop as well. This seems to be the case on the client side, but not the server side. If the server disconnects from the client, the client stops syncing, but if the client disconnects from the server, the server will happily connect again without failing first. If the server were to stop on client disconnect it should stop issues of accidentally switching one end without the other.

The obvious problem with these are they're large design changes, not simple fixes. I feel this would make Rojo a more robust tool though.

**Comment by LPGhatguy** [comment] 2018-06-14 17:46
Rojo is intended to be your live development model. When iterating on code, manually syncing doesn't make any sense unless you distrust the tool you're using.

The mental model I'm trying to push for, especially with the new rewrite, is not that you make changes to either Roblox or the filesystem and commit them, it's that they are just inherently in sync with eachother. Crossing the boundary should be totally transparent. You shouldn't _need_ manual syncing in a world where that works.

You connect to a Rojo instance, and pick which side has the latest work. Multiple clients should be able to connect to a Rojo project at once -- I'm hoping to build a bundled web UI for configuring and diagnosing problems with the server.

Putting code into your place isn't committing to version control, it's making it so you can test your game/plugin/library. Every manual step that you have to take to actually run your game makes Rojo worse than developing in studio!

Another approach that I thought about as opposed to random ports would be to use a large, pre-determined port. When a Rojo instance starts up, it spawns a quasi-reference-counted daemon server, and then uses an RPC/pub-sub hybrid mechanism to connect to it, as would the plugin and any clients.

**Comment by LastTalon** [comment] 2018-06-15 00:53
That approach sounds more limiting though because it will always present workflow and collaboration issues like this unless that specific workflow has been considered already. Whereas if it had an actual push/pull system automated syncing can be built on top of that in a robust way to make a more ideally seamless system.

In addition, not everyone wants to use the same work flow with every tool. Its not about trusting your tools, its about fine-grain control over how the tool syncs your work. If a tool doesn't support the control a user needs is not fit for purpose.

The issue is really that there isn't a big enough distinction between the basic syncing tool and the automatic syncing through the server. A server daemon would definitely help in this respect, but while automatic syncing is going on, there's still no distinction made until a change happens as to which project the opposite end is attached to. Based on this I think the best option would be to have single-user commands for individual pull/push, a single-user interactive mode server daemon in which disconnecting one endpoint would disconnect the other to prevent unintentionally swapping the project on one end but not the other, and then a multi-user dedicated mode daemon which you could then accept multiple connections. If the daemons simply access the normal push/pull functionality of the tool, then end to end it doesn't matter how you're connecting, you can simply push/pull individually or automatically syncing without a change to the server operation on the other end.

**Comment by LPGhatguy** [comment] 2019-01-04 22:16
This is solved in Git master (Epiphany) now with a few features:
- The plugin now spawns an address/port prompt dialog
- Projects can have a field named `servePort` saved in their configuration, which was present but useless in 0.4.x
- Projects can have a field named `servePlaceIds`, which is a list of place IDs that should be accepted when connecting to the Rojo server

Now it should be difficult to accidentally sync content to or from the wrong place.

**Closed by LPGhatguy** 2019-01-04 22:16 UTC
Labels: feature: planned
